#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xb2,0x4f,0x85,0x3c,0x18,0xbd,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xb2,0x4f,0x85,0x3c,0x3f,0xcd,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
